Vagrant.configure("2") do |config|
  config.vm.box = "mvbcoding/awslinux"
  config.vm.box_url = "https://app.vagrantup.com/mvbcoding/boxes/awslinux"

  # NOTICE:
  #   This configiration needs a plugin called "vagrant-disksize".
  #   You have to install the plug-in with the command below.
  #   $ vagrant plugin install vagrant-disksize
  config.disksize.size = '30GB'
  
  config.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus = 1
  end


  # This VM uses "Private Networks" described on the document below.
  # https://www.vagrantup.com/docs/networking/private_network.html
  config.vm.define :"vm1private" do |c1|
    c1.vm.hostname = "vm1private"
    c1.vm.network "private_network",ip: "192.168.255.21"
  end

  config.vm.define :"vm3private" do |c3|
    c3.vm.hostname = "vm3private"
    c3.vm.network "private_network",ip: "192.168.254.23"
  end

  # This VM uses "Public Networks" described on the document below.
  # https://www.vagrantup.com/docs/networking/public_network.html
  config.vm.define :"vm2public" do |c2|
    c2.vm.hostname = "vm2public"
    c2.vm.network "public_network"
  end

  config.ssh.insert_key = false

  config.vm.provision :shell, :path => "bootstrap.sh"
  config.vm.synced_folder "../", "/home/vagrant/local_workspace"

end

