Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-12.6"
 
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 4
  end

  config.vm.define :"stdsv9" do |c1|
    c1.vm.hostname = "stdsv9"
    c1.vm.network "private_network",ip: "192.168.255.17"
  end

  config.vm.provision :shell, :path => "bootstrap.sh"
  config.vm.synced_folder "../", "/home/vagrant/local_workspace" , mount_options: ['dmode=755','fmode=755']
  config.vm.synced_folder "../../", "/home/vagrant/projects" , mount_options: ['dmode=755','fmode=755']
end

