Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
 
  config.vm.provider "vmware_desktop" do |v|
    v.memory = 1024
    v.cpus = 1
  end

  config.vm.define :"stdsv7" do |c1|
    c1.vm.hostname = "stdsv7"
    c1.vm.network "private_network",ip: "192.168.254.15"
  end

  config.vm.provision :shell, :path => "bootstrap.sh"

  config.vm.synced_folder "../", "/home/vagrant/local_workspace" , type: "smb"
  config.vm.synced_folder "../../", "/home/vagrant/projects" , type: "smb"
end

