#
# common role
#

- name: Configure sshd service name for RedHat family
  include_vars: vars-RedHat.yml
  when: (ansible_os_family == "RedHat")

- name: Configure sshd service name for Debian family
  include_vars: vars-Debian.yml
  when: (ansible_os_family == "Debian")


- name: Install necessary packages.
  yum:
    name:
     - git
     - jq
     - screen
    update_cache: yes

- name: Install auto completion configuration for AWS CLI
  copy: src=aws-cli-bash.sh dest=/etc/profile.d/aws-cli-bash.sh mode=755 owner=root group=root

- name: Configure "screen" for all users 1/2
  lineinfile: dest=/etc/screenrc state=present line="escape ^]]"
- name: Configure "screen" for all users 2/2
  lineinfile: dest=/etc/screenrc state=present line="termcapinfo xterm 'is=\E[r\E[m\E[2J\E[H\E[?7h\E[?1;4;6l'"

- name: Change sshd to accept "PasswordAuthentication"
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: 'PasswordAuthentication .*'
    line: 'PasswordAuthentication yes'
    state: present
  notify: reload sshd service

- name: Make default editor vim on Ubuntu
  alternatives:
    name: editor
    path: /usr/bin/vim.basic
  when: (ansible_os_family == 'Debian' and ansible_distribution == 'Ubuntu')

