VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos/7"
  config.vm.box = "geerlingguy/centos7"
  config.vm.box_url = "https://app.vagrantup.com/geerlingguy/centos7"
  config.vm.box_version = "1.2.9"
  config.vm.boot_timeout = 600
  config.vm.provision :shell, :path => "bootstrap.sh"

  config.vm.synced_folder "../", "/home/vagrant/local_workspace"
  config.vm.synced_folder "../../", "/home/vagrant/projects"

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
  end

  config.vm.network "forwarded_port", guest:22, host:2322
  config.vm.define :stdsv1 do |c1|
    c1.vm.hostname = "stdsv1"
    c1.vm.network :private_network, ip: "192.168.255.11"
  end
end
