Vagrant.configure("2") do |config|
  config.vm.box = "gbailey/amzn2"

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
  end

  config.vm.define :"manager1" do |h1|
    h1.vm.hostname = "manager1"
    h1.vm.network "private_network",ip: "192.168.255.21"
  end

  config.vm.define :"registry1" do |h2|
    h2.vm.hostname = "registry1"
    h2.vm.network "private_network",ip: "192.168.255.24"
  end

  config.vm.define :"worker1" do |h3|
    h3.vm.hostname = "worker1"
    h3.vm.network "private_network",ip: "192.168.255.26"
  end

  config.vm.define :"worker2" do |h4|
    h4.vm.hostname = "worker2"
    h4.vm.network "private_network",ip: "192.168.255.27"
  end

  config.vm.provision :shell, :path => "bootstrap.sh"
  config.vm.synced_folder "../", "/home/vagrant/local_workspace" , mount_options: ['dmode=755','fmode=755']
  config.vm.synced_folder "../../", "/home/vagrant/projects" , mount_options: ['dmode=755','fmode=755']

end

