#
# common_docker
#

- name: Install Docker on an Amazon Linux 2
  include_tasks: setup-AmazonLinux2.yml
  when:
    - ansible_distribution == "Amazon" and ansible_service_mgr =='systemd'

- name: Install Docker on Debian
  include_tasks: setup-Debian.yml
  when:
    - (ansible_os_family == 'Debian')

- name: Install Docker on CentOS 7
  include_tasks: setup-CentOS7.yml
  when:
    - (ansible_distribution == 'CentOS') and (ansible_distribution_major_version == '7')


- name: Make login users be able to invoke docker commands
  user:
    name: "{{login_user_name}}"
    groups: "{{docker_groupname}}"
    append: yes
