#
# common_docker
#
---

# Amazon Linux 2023
- name: Install Docker on Amazon Linux 2023
  include_tasks: setup-AmazonLinux2023.yml
  when:
    - ansible_distribution == "Amazon"
    - ansible_distribution_major_version == "2023"

# Ubuntu 22
- name: Install Docker on Ubuntu 22
  include_tasks: setup-Ubuntu22.yml
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version == "22"

# Debian
- name: Install Docker on Debian
  include_tasks: setup-Debian.yml
  when:
    - ansible_distribution == "Debian"

# Setting up Docker group
- name: Make login users be able to invoke docker commands
  user:
    name: "{{login_user_name}}"
    groups: "{{docker_groupname}}"
    append: yes
