Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
 
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
  end

  config.vm.define :"stdsv6" do |c1|
    c1.vm.hostname = "stdsv6"
    c1.vm.network "private_network",ip: "192.168.255.14"
  end

  config.vm.provision :shell, :path => "bootstrap.sh"
  config.vm.synced_folder "../", "/home/vagrant/local_workspace" , mount_options: ['dmode=755','fmode=755']
  config.vm.synced_folder "../../", "/home/vagrant/projects" , mount_options: ['dmode=755','fmode=755']
end

