Vagrant.configure("2") do |config|
  config.vm.box = "gbailey/al2023"
 
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 4
  end

  config.vm.define :"stdsv10" do |c1|
    c1.vm.hostname = "stdsv10"
    c1.vm.network "private_network",ip: "192.168.255.18"
  end

  config.vm.provision :shell, :path => "bootstrap.sh"
  config.vm.synced_folder "../", "/home/vagrant/local_workspace" , mount_options: ['dmode=755','fmode=755']
  config.vm.synced_folder "../../", "/home/vagrant/projects" , mount_options: ['dmode=755','fmode=755']

  config.vm.synced_folder ENV['USERPROFILE'] + "/.ssh", "/home/vagrant/.ssh" , mount_options: ['dmode=700','fmode=700']
  config.vm.synced_folder ENV['USERPROFILE'] + "/.aws", "/home/vagrant/.aws" , mount_options: ['dmode=700','fmode=700']

end

