Vagrant.configure("2") do |config|
  config.vm.box = "mvbcoding/awslinux"
  config.vm.box_url = "https://app.vagrantup.com/mvbcoding/boxes/awslinux"

  # NOTICE:
  #   This configiration needs a plugin called "vagrant-disksize".
  #   You have to install the plug-in with the command below.
  #   $ vagrant plugin install vagrant-disksize
  config.disksize.size = '30GB'
  
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
  end

  config.vm.define :"stdsv2" do |c1|
    c1.vm.hostname = "stdsv2"
    c1.vm.network "private_network",ip: "192.168.255.12"
  end

  config.ssh.insert_key = false

  #config.vbguest.auto_update = false
  config.vm.provision :shell, :path => "bootstrap.sh"
  config.vm.synced_folder "../", "/home/vagrant/local_workspace"
  config.vm.synced_folder "../../", "/home/vagrant/projects"

end

