Vagrant.configure("2") do |config|
  config.vm.box = "mvbcoding/awslinux"
  config.vm.box_url = "https://app.vagrantup.com/mvbcoding/boxes/awslinux"

  # NOTICE:
  #   This configiration needs a plugin called "vagrant-disksize".
  #   You have to install the plug-in with the command below.
  #   $ vagrant plugin install vagrant-disksize
  config.disksize.size = '30GB'
  
  config.vm.provider "virtualbox" do |v|
    v.memory = 1536
    v.cpus = 1
  end

  config.vm.define :"stdsv2" do |c1|
    c1.vm.hostname = "stdsv2"
    c1.vm.network "private_network",ip: "192.168.255.12"
    c1.vm.network "forwarded_port", guest:3000, host:3000
    c1.vm.network "forwarded_port", guest:8121, host:8121
    c1.vm.network "forwarded_port", guest:8122, host:8122
    c1.vm.network "forwarded_port", guest:8123, host:8123
    c1.vm.network "forwarded_port", guest:8124, host:8124
    c1.vm.network "forwarded_port", guest:8125, host:8125
  end

  config.ssh.insert_key = false

  #config.vbguest.auto_update = false
  config.vm.provision :shell, :path => "bootstrap.sh"
  config.vm.synced_folder "../", "/home/vagrant/local_workspace" , mount_options: ['dmode=755','fmode=755']
  config.vm.synced_folder "../../", "/home/vagrant/projects" , mount_options: ['dmode=755','fmode=755']

end

