Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
 
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
  end

  config.vm.define :"stdsv8" do |c1|
    c1.vm.hostname = "stdsv8"
    c1.vm.network "private_network",ip: "192.168.255.16"
  end

  config.vm.provision :shell, :path => "bootstrap.sh"
  config.vm.synced_folder "../", "/home/vagrant/local_workspace" , mount_options: ['dmode=755','fmode=755']
  config.vm.synced_folder "../../", "/home/vagrant/projects" , mount_options: ['dmode=755','fmode=755']

  config.vm.synced_folder ENV['USERPROFILE'] + "/.ssh", "/home/vagrant/.ssh" , mount_options: ['dmode=700','fmode=700']
  config.vm.synced_folder ENV['USERPROFILE'] + "/.aws", "/home/vagrant/.aws" , mount_options: ['dmode=700','fmode=700']

end

